backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
- name: "pages"
  label: "Pages"
  files:
    - file: "content/_index.md"
      label: "Home Page"
      name: "home"
      fields:
        - {label: "Welcome", name: welcome, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Tagline", name: "tagline", widget: "text"}]}
        - {label: "What we do", name: what_we_do, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Description", name: description, widget: "markdown"},
            {label: "Image", name: image, widget: image},
            {label: "Image Caption Name", name: name, widget: string},
            {label: "Image Caption Position", name: position, widget: string}]}
        - {label: Services, name: services, widget: list, fields: [
            {label: Service, name: service, widget: object, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Icon Right, name: icon_right, required: false, widget: boolean},
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown}
            ]},
            {label: Testimonial, name: testimonial, widget: object, fields: [
              {label: Image, name: image, widget: image},
              {label: Text, name: text, widget: markdown}
            ]}
          ]}
        - {label: Trainings, name: trainings, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Training Cards, name: training_cards, widget: list, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Description, name: description, widget: text}
            ]},
            {label: Training Table, name: training_table, widget: list, fields: [
              {label: Title, name: title, widget: string},
              {label: Text, name: text, widget: markdown}
            ]},
            {label: Timeline, name: timeline, widget: object, fields: [
              {label: Days, name: days, widget: string},
              {label: Week, name: weeks, widget: string},
              {label: Ongoing, name: ongoing, widget: string}
            ]}
          ]}
        - {label: How To Use, name: how_to_use, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Placeholder Image, name: image, widget: image},
            {label: Video Link, name: video, widget: file},
          ]}
- name: "site"
  label: "Site"
  files:
    - file: "data/footer/footer.yml"
      label: "Footer"
      name: "footer"
      fields:
        - {label: Logo, name: logo, widget: image}
        - {label: Footer Nav Column, name: footer_col, widget: list, fields: [
            {label: Title, name: title, widget: string},
            {label: Footer Nav Item, name: footer_item, widget: list, fields: [
              {label: Item Name, name: name, widget: string},
              {label: Item Link, name: link, widget: string}
            ]}
          ]}
        - {label: Footer Button, name: footer_btns, widget: list, fields: [
            {label: Button Title, name: title, widget: string},
            {label: Button Link, name: link, widget: string},
          ]}
        - {label: Policy Links, name: policy_links, widget: list, fields: [
            {label: Title, name: title, widget: string},
            {label: Link, name: link, widget: string},
          ]}
